### PR TITLE
Fixes CLOB newline processing.

### LINKED ISSUE #3: Fix CLOB Newline Normalization
https://github.com/amzn/ion-tests/commit/2a1f3f4f272256108e89f1c53bfae5b3a9ede812 introduces CLOB newline normalization in text.  This is currently skipped in the parser tests.

### PR DESCRIPTION
**Pull request by almann**
Also adds escape processing in CLOB parsing to support `\xHH` escapes
which is part of #18.

#17 asks a larger question about the factoring around escape logic
in the parser, which this commit does not aim to address.

Fixes #3

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: ion/parse_text_simple.go [hunk 1]
```diff
@@ -115,7 +115,7 @@ func doStringReplacements(str []byte) []byte {
 	return ret
 }
 
-// doClobReplacements is like doStringReplacements, but keeps \r characters as-is.
+// doClobReplacements is like doStringReplacements but is restricted to escapes that CLOBs have
```
Comment (mrutter-amzn) [inline ion/parse_text_simple.go]: Nitpick: period

File: ion/parse_text_simple.go [hunk 2]
```diff
@@ -124,11 +124,9 @@ func doClobReplacements(str []byte) []byte {
 		case '\r':
 			// We need to treat "\r\n" as "\n", so skip extra if what comes next is "\n".
```
Comment (mrutter-amzn) [inline ion/parse_text_simple.go]: Update the comment since we are also normalizing `\r` to `\n`.

It's strange, this code is like this because there was a test that was failing if I didn't retain `\r`.  *shrug*.

File: ion/parse_text_simple.go [hunk 3]
```diff
@@ -155,6 +153,12 @@ func doClobReplacements(str []byte) []byte {
 			case '\'', '"', '\\':
 				ret = append(ret, next)
 				index++
+			case 'x':
+				// Decode the hex sequence
+				index += 2
+				octet, _ := strconv.ParseUint(string(str[index:index+2]), 16, 8)
```
Comment (mrutter-amzn) [inline ion/parse_text_simple.go]: Unprotected array index access after increment.  Also lacking handling if what is being escaped is an invalid hex number.

Comment (almann) [reply ion/parse_text_simple.go]: It is technically an invariant from the lexer, would it be okay to panic in this case?

File: ion/parse_text_simple.go (hunk 2 above)
Comment (almann) [reply ion/parse_text_simple.go]: Fixed.

File: ion/parse_text_simple.go (hunk 1 above)
Comment (almann) [reply ion/parse_text_simple.go]: Fixed.

File: ion/parse_text_simple.go (hunk 3 above)
Comment (almann) [reply ion/parse_text_simple.go]: Actually, I checked and this is fixed in #20, so unless you object, I would defer to that PR.

Comment (mrutter-amzn) [reply ion/parse_text_simple.go]: That's fine.  As to the general question - if it should be an invariant of the lexer then a panic with a message that includes contextual details would be warranted.
