### PR TITLE
Fixes String/Symbol hex escape processing.

### LINKED ISSUE #18: Fix Unicode and Hex Escape Parsing in String/Symbol/CLOB
As per #17, there appears to be an issue around escape processing for Unicode escapes (i.e. `\uHHHH`, `\UHHHHHHHH`, and `\xHH`), we should make sure this is working correctly in parser, because for at least CLOBs, `\xHH` does not appear to process correctly when parsing `clobNewlines.ion` in the test vectors.

### PR DESCRIPTION
**Pull request by almann**
* Removes `unquoted` field and use of `strconv.Unquote` from `String`.
* Unifies `\x`, `\u`, and `\U` processing in `parse_text_simple.go`
  for CLOB and String/Symbol.

Incremental improvement towards #17.  There is a bit more DRY than
I'd prefer in the String/Symbol switch statements, but I think it
is important to get these fixes out and address that more as a
follow-up for the lexer/parser refactor.

Depends on #19

Fixes #18

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: ion/parse_text_simple.go [hunk 1]
```diff
@@ -56,15 +57,43 @@ func (p *parser) parseBinary(annotations []Symbol) Value {
...
+		text = append(text, p.doStringReplacements(p.next().Val)...)
 	}
 
 	return String{annotations: annotations, text: text}
 }
 
+// decodeHex takes a slice that is a hex-encoded rune (up to 4 bytes large)
+// and decodes it into a slice containing UTF-8 code units.
+func (p *parser) decodeHex(hex []byte) []byte {
+	// must be a power of two and no larger that uint32
```
Comment (mrutter-amzn) [inline ion/parse_text_simple.go]: Nitpick: `Must be a power of two and no larger than uint32.`

File: ion/parse_text_simple.go [hunk 2]
```diff
@@ -56,15 +57,43 @@ func (p *parser) parseBinary(annotations []Symbol) Value {
...
+	hexLen := len(hex)
+	if hexLen <= 0 || hexLen > 8 || hexLen%2 != 0 {
+		// calling code must give us a proper slice...
+		p.panicf("Unexpected hex slice handed to decoder: %v", hex)
```
Comment (mrutter-amzn) [inline ion/parse_text_simple.go]: Nitpick: This message doesn't give me any hints as to what constraints were violated.  The comment on line 69 seems like a pretty good start =)

File: ion/parse_text_simple.go [hunk 3]
```diff
@@ -56,15 +57,43 @@ func (p *parser) parseBinary(annotations []Symbol) Value {
...
+	}
+
+	// decode the hex string into a UTF-32 scalar
+	var cp uint64
+	buf := make([]byte, utf8.UTFMax)
+	for i := 0; i < hexLen; i += 2 {
+		octet, ok := strconv.ParseUint(string(hex[i:i+2]), 16, 8)
```
Comment (mrutter-amzn) [inline ion/parse_text_simple.go]: `ok` is for `bool`.  `err` is for `error`.  In this case I would call it `errParse`.

File: ion/parse_text_simple.go [hunk 4]
```diff
@@ -56,15 +57,43 @@ func (p *parser) parseBinary(annotations []Symbol) Value {
...
+		if ok != nil {
+			// invariant technically violated as the lexer should have validated this
+			p.panicf("bad hex literal not processed by lexer: %v", hex)
```
Comment (mrutter-amzn) [inline ion/parse_text_simple.go]: Suggestion: `bad hex literal not caught by the lexer: %v`

File: ion/parse_text_simple.go [hunk 5]
```diff
@@ -56,15 +57,43 @@ func (p *parser) parseBinary(annotations []Symbol) Value {
...
+	// must be a power of two and no larger that uint32
+	hexLen := len(hex)
+	if hexLen <= 0 || hexLen > 8 || hexLen%2 != 0 {
+		// calling code must give us a proper slice...
+		p.panicf("Unexpected hex slice handed to decoder: %v", hex)
+	}
+
+	// decode the hex string into a UTF-32 scalar
+	var cp uint64
+	buf := make([]byte, utf8.UTFMax)
```
Comment (mrutter-amzn) [inline ion/parse_text_simple.go]: Nitpick: Declare this closer to where it's used.

File: ion/parse_text_simple.go [hunk 6]
```diff
@@ -101,6 +130,21 @@ func doStringReplacements(str []byte) []byte {
...
+			case 'u':
+				index += 2
+				data := p.decodeHex(str[index : index+4])
+				index += 3
+				ret = append(ret, data...)
+			case 'U':
+				index += 2
+				data := p.decodeHex(str[index : index+8])
+				index += 7
+				ret = append(ret, data...)
```
Comment (mrutter-amzn) [inline ion/parse_text_simple.go]: A lot of unchecked slice indexing.

File: ion/parse_text_simple.go (hunk 2 above)
Comment (almann) [reply ion/parse_text_simple.go]: Done.

File: ion/parse_text_simple.go (hunk 3 above)
Comment (almann) [reply ion/parse_text_simple.go]: Fixed.

Comment (almann) [reply ion/parse_text_simple.go]: Fixed.

File: ion/parse_text_simple.go (hunk 5 above)
Comment (almann) [reply ion/parse_text_simple.go]: Fixed.

File: ion/parse_text_simple.go (hunk 6 above)
Comment (almann) [reply ion/parse_text_simple.go]: Refactoring this into `decodeHex` to have that do all the bounds checking.

File: ion/parse_text_simple.go (hunk 5 above)
Comment (almann) [reply ion/parse_text_simple.go]: Fixed.

File: ion/parse_text_simple.go (hunk 4 above)
Comment (almann) [reply ion/parse_text_simple.go]: Fixed.

File: ion/parse_text_simple.go (hunk 1 above)
Comment (almann) [reply ion/parse_text_simple.go]: Done.
